// Vinita's "100 Gentle Reminders to Be Kind to Yourself", shown to Companion
// members as a daily note from her. Each is written to be read at any hour
// (framed as "Today, ..."), so it lands whenever a member opens the app — not
// only first thing in the morning. Verbatim from her document; do not reword.
export const KINDNESS_REMINDERS: string[] = [
  "Today, please speak to yourself a little more gently. You are listening.",
  "You don’t have to earn rest. If you are tired, rest. That is reason enough.",
  "I hope today you forgive yourself for something you did when you were only trying to survive.",
  "Please don’t use one difficult moment as proof that you are failing. It is just a moment.",
  "You are allowed to have a slow day without calling yourself lazy.",
  "Before you criticize yourself today, ask: would I say this to someone I deeply love?",
  "You have carried enough. You don’t have to carry everything today.",
  "Some days, getting through the day is an achievement. Please count it.",
  "You are allowed to change your mind when something no longer feels right for you.",
  "Please stop punishing yourself for not knowing then what you know now.",
  "Your body has been carrying you through every season of your life. Speak to it with kindness today.",
  "You don’t need to explain every boundary. Sometimes “I can’t” is enough.",
  "I hope you choose yourself today, even in one small way.",
  "Not everything needs to be fixed immediately. Some things need time, space, and softness.",
  "Please remember, your worth does not decrease on the days you are less productive.",
  "You are not behind. Your life is not a race against someone else’s timeline.",
  "If your heart feels heavy today, don’t force it to be cheerful. Sit beside it gently.",
  "You are allowed to miss someone and still know they are not good for you.",
  "Please don’t abandon yourself just to keep someone else comfortable.",
  "Today, do one thing that makes your nervous system feel safe.",
  "You deserve the same patience you so easily give to everyone else.",
  "It is okay if you are still healing from something you thought you had moved on from.",
  "Please eat something nourishing today. Your body deserves care, not punishment.",
  "You don’t have to answer every message immediately. Your availability is not proof of your love.",
  "If you made a mistake, correct what you can and then let yourself remain human.",
  "Please don’t compare your private struggles with someone else’s visible success.",
  "You are allowed to celebrate small progress. Small does not mean insignificant.",
  "Today, notice how often you rush yourself. Then gently say, “I have time.”",
  "You don’t need everyone to understand you in order to trust what you feel.",
  "Please remember that saying no can also be an act of love toward yourself.",
  "You have survived days you once thought would break you. Be proud of the person who kept going.",
  "Rest is not a reward for exhaustion. You can rest before you collapse.",
  "I hope you stop shrinking your needs just because someone once made you feel like they were too much.",
  "Today, let one thing be imperfect. The world will continue.",
  "Please don’t measure your entire life by what you achieved this week.",
  "You are allowed to begin again without hating the version of you who stopped.",
  "If you need help, ask. Being supported does not make you weak.",
  "Please speak kindly to the version of you who made choices from fear. They needed safety, not shame.",
  "You don’t have to turn every painful experience into a lesson today. Sometimes pain is simply pain.",
  "Take a moment and unclench your jaw. Drop your shoulders. Your body may be holding what your words haven’t said.",
  "Please don’t chase people who repeatedly make you question whether you matter.",
  "You are allowed to protect your peace, even if someone calls it distance.",
  "Today, give yourself permission to do less than your maximum.",
  "Your feelings are not an inconvenience. Listen to what they are trying to show you.",
  "Please remember that healing is not always visible. Quiet changes still count.",
  "You don’t need to be positive all the time to be a good person.",
  "I hope you stop apologizing for needing clarity, respect, and consistency.",
  "Today, choose comfort without guilt. Wear the soft clothes. Take the longer shower. Sit in the sun.",
  "Please don’t speak to yourself in the voice of someone who once hurt you.",
  "You are allowed to outgrow places where you once begged to belong.",
  "If today feels difficult, make the day smaller. Just focus on the next hour.",
  "Please remember, you do not need to solve your whole life before bedtime.",
  "You are worthy of love even when you are confused, tired, quiet, or uncertain.",
  "Today, notice one thing you did well instead of only counting what went wrong.",
  "You don’t have to keep proving that you are strong. You are allowed to be held too.",
  "Please forgive yourself for the boundaries you didn’t know how to set earlier.",
  "Some people may misunderstand your growth because they benefited from your lack of boundaries. Keep growing.",
  "Today, don’t force an answer. Clarity often comes when pressure leaves.",
  "Please let yourself enjoy something without asking whether you have earned it.",
  "You are allowed to take up space in rooms where you once made yourself small.",
  "If someone’s silence is hurting you, please don’t fill that silence with stories about your unworthiness.",
  "Today, choose one thought about yourself that feels kinder than yesterday’s.",
  "Please remember, you can love people and still choose distance.",
  "You are not required to stay loyal to a version of yourself you have outgrown.",
  "If you feel overwhelmed, reduce the expectations. You do not need to reduce your worth.",
  "Please stop calling yourself difficult for having needs.",
  "Today, let your body set the pace for a little while.",
  "You are allowed to be proud of how far you have come, even if you still have far to go.",
  "Please don’t turn someone else’s inability to love you well into evidence that you are hard to love.",
  "You deserve relationships where you don’t have to constantly decode how someone feels about you.",
  "Today, place your hand on your heart and ask, “What do I need?” Then listen without judgment.",
  "Please remember, choosing yourself may disappoint people who were comfortable with you choosing them first.",
  "You don’t have to be available simply because someone wants access to you.",
  "If you are tired, perhaps you need compassion more than motivation today.",
  "Please don’t rush your healing to make other people comfortable with your pain.",
  "Today, release one expectation that is making you feel like you are not enough.",
  "You are allowed to have boundaries with people you love deeply.",
  "Please remember that your younger self is still learning from the way you treat yourself now.",
  "You don’t have to look beautiful, feel confident, and be productive every day to deserve tenderness.",
  "Today, choose the kinder interpretation of yourself.",
  "Please stop asking, “What is wrong with me?” Try asking, “What is hurting in me?”",
  "You are allowed to grieve the life you thought you would have.",
  "If you need a fresh start, you don’t need permission. Begin quietly.",
  "Please remember, being kind to yourself does not mean avoiding responsibility. It means correcting yourself without cruelty.",
  "Today, don’t make a permanent judgment about yourself based on a temporary emotion.",
  "You can be grateful for your life and still admit that something hurts.",
  "Please don’t confuse being needed with being loved.",
  "Today, protect at least ten minutes that belong only to you.",
  "You are allowed to stop explaining yourself to people committed to misunderstanding you.",
  "Please remember, your softness is not something you need to lose in order to become strong.",
  "If all you did today was keep yourself together, I hope you know that counts too.",
  "You don’t have to heal beautifully. You can heal messily, slowly, privately.",
  "Please offer yourself the apology you keep waiting to receive from someone else: “I am sorry I abandoned you. I am here now.”",
  "Today, let yourself be a person, not a project that constantly needs improvement.",
  "You are allowed to want more for your life without being ungrateful for what you have.",
  "Please remember, you are not responsible for managing everyone’s emotions at the cost of your own.",
  "If your heart is asking for rest, don’t answer it with more pressure.",
  "Today, choose yourself in one place where you usually disappear.",
  "Please be patient with the person you are becoming. New versions of you need time to feel like home.",
  "And if no one has reminded you lately, let me remind you: you deserve your own kindness too. Not someday. Not after you fix everything. Today.",
];

// Deterministic daily rotation: everyone sees the same reminder on a given day,
// advancing by one each day and cycling through all 100 (~3+ months, then it
// gently repeats). Kept server-side so the popup and the profile card always
// show the same note for "today".
export function kindnessIndexForDay(date: Date = new Date()): number {
  const dayNumber = Math.floor(date.getTime() / 86_400_000);
  const n = KINDNESS_REMINDERS.length;
  return ((dayNumber % n) + n) % n;
}

export function todaysKindness(date: Date = new Date()): string {
  return KINDNESS_REMINDERS[kindnessIndexForDay(date)];
}
